### ISSUE TITLE
com.osiris.payhook.PayHook#validateWebhookEvent The method does not set webhook_id under the sandbox, and will always return "FAILURE"

### ISSUE THREAD

**Issue by fendo8888** [Osiris-Team/PayHook#2]
com.osiris.payhook.PayHook#validateWebhookEvent The method does not set webhook_id under the sandbox, and will always return "FAILURE"

![image](https://user-images.githubusercontent.com/22114481/180165582-29ae30f9-8052-445c-926f-6d4fbd2e9705.png)

![image](https://user-images.githubusercontent.com/22114481/180165447-ea76a18c-9378-4f13-9f29-e2fb04098151.png)

**Comment by Osiris-Team** [comment]
Oh dammn, can you submit a PR to fix that?

**Comment by fendo8888** [comment]
> Oh dammn, can you submit a PR to fix that?

![image](https://user-images.githubusercontent.com/22114481/180166813-b4b971c4-3652-48d8-b5d4-ffbba8bd7752.png)

I'm not very familiar with it, I don't know how to change it, haha

**Comment by fendo8888** [comment]
PayHook payHook = new PayHook(PayHookValidationType.OFFLINE,clientId, clientSecret)  Use offline initialization to use

**Comment by Osiris-Team** [comment]
@fendo8888 could it be that the webhook id is always null when its in sandbox mode? Think I read something about that somewhere.

**Comment by fendo8888** [comment]
> @fendo8888 could it be that the webhook id is always null when its in sandbox mode? Think I read something about that somewhere.

YES

**Comment by Osiris-Team** [comment]
Well then I guess this can be closed
